AVIARY-3275 - tokenfield changes for search
WeAreAVP/aviary-public pull request #222
Opened 2022-09-27 16:53 UTC by rubab

2022-09-29 11:23 UTC, furqanwasi requested changes

2022-09-29 11:23 UTC, furqanwasi commented on app/views/interviews/managers/_form.html.erb
> +    new Tokenfield({
this code should be in related JS file e.g. InterviewManager

2022-09-29 11:39 UTC, rubab commented on app/views/interviews/managers/_form.html.erb
> +    new Tokenfield({
already moved.

2022-09-30 08:52 UTC, furqanwasi approved these changes

2022-09-30 08:52 UTC, merged