AVIARY-3273 - Share links accessible with tab
WeAreAVP/aviary-public pull request #227
Opened 2022-10-05 09:10 UTC by rubab

2022-10-05 15:27 UTC, furqanwasi requested changes

2022-10-05 15:27 UTC, furqanwasi commented on app/assets/javascripts/accessibility.js
> +            console.log("from file")
same here as private

2022-10-05 15:27 UTC, furqanwasi commented on app/assets/javascripts/accessibility.js
> +            console.log("from file on load")
same here as private

2022-10-06 06:26 UTC, rubab commented on app/assets/javascripts/accessibility.js
> +            console.log("from file on load")
console removed

2022-10-06 06:26 UTC, rubab commented on app/assets/javascripts/accessibility.js
> +            console.log("from file")
console removed

2022-10-06 07:09 UTC, furqanwasi approved these changes

2022-10-06 07:09 UTC, merged